spring:
  application:
    name: diet
  data:
    mongodb:
      uri: mongodb://localhost:27017/my_local_db # mongodb://localhost:27017/
      auto-index-creation: true
      uuid-representation: standard
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: #${GOOGLE_CLIENT_ID}
            client-secret: #${GOOGLE_CLIENT_SECRET}
server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /api
